@startuml
start
  :""Dashboard Group::create(dry_run?, force?, interactive?)"";
  if (dry_run?) then (yes)
    :return request to caller;
    stop
  else (no)
    partition "Dashboard Group Create" {
        if (found results?) then (yes)
          if (exact match?) then (yes)
            if (force?) then (yes)
              : Get Dashboard Group Id;
              #Orange:**POST** /v2/dashboardgroup>
            elseif (interactive?) then (yes)
              if (confirm resource update?) then (yes)
                : Get Dashboard Group Id;
                #Orange: **PUT** /v2/dashboardgroup/<id> >
              else (no)
                #OrangeRed: raise ResourceAlreadyExistsError;
                stop
              endif
            else (no)
              #OrangeRed:raise ResourceAlreadyExistsError;
              stop
            endif
          else (no)
            #Orange:**POST** /v2/dashboardgroup>
          endif
        else (no)
          #Orange:**POST** /v2/dashboardgroup>
        endif
    }
    : Get Dashboard Group Id;
    : Get the Dashboard Id of the default dashboard
      that is creates as part of the Dashboard Group;
    if (is Dashboard resource provided?) then (yes)
        #Orange: ""Dashboard::create(dry_run?, force?, interactive?)"" >
        note right
            Follows Dashboard Create logic
        end note
        : Get Dashboard Id;
        #Orange: **POST** /v2/dashboardgroup/<id>/dashboard >
        note right
        Clone the Dashboard that was created by giving the `sourceDashboard` as the
        Dashboard Group Id that was initially created
        end note
        #Orange: **GET** v2/dashboardgroup/<id> >
        note right
        Verify that the Dashboard is cloned to the Dashboard Group we created
        end note
        #Orange: **DELETE** v2/dashboardgroup/<id> >
        note right
        Delete the already cloned Dashboard Group
        end note
        #Orange: **DELETE** v2/dashboard/<id> >
        note right
        Delete the orphan dashboard that was created by default in the final Dashboard Group
        end note
     else (no)
        stop
     endif
     stop
  endif
@enduml
