@startuml
start
  :Dashboard::pre_update(signalfx_config, payload);
  note right
    All orange right arrows imply
    error handling against the declared
    exceptions for the method.
  end note
  #Orange:**GET** chart configuration for each chart id in signalfx_config >
  :build set of charts to update;
  note right
    chart exists both in signalfx_config and local config
  end note
  :build set of charts to delete;
  note right
    chart exists in signalfx_config but **not** local config
  end note
  :build set of charts to create;
  note right
    chart does **not** exist in signalfx_config but **does** in local config
  end note
  repeat
    :for each set of charts...;
    :perform required state change on resource;
    :update signalfx_config;
  repeat while (more charts to process)
  #SpringGreen:return modified signalfx_config;
  stop
@enduml
