language: python
python:
  - '2.7'
  - '3.6'
install:
  - pip install .
  - pip install -r requirements_dev.txt
script:
  - make test
cache:
  directories:
    - "./.hypothesis"
deploy:
  provider: pypi
  user: nikeoss
  password:
    secure: "MSsqG2ksNDKCOF/k6uqpZ1cVC6oXcLcJqeofU40jtvPcrK3pMy0uYIQ5lCLdpwUm9sCKTe/8tF2WTR75EAEtYa7vGPFPFggsJ7T5JEJKhpP1XJEfVMBQPQgczmzAXhR/0ugJe4VqNCQPhahC34vDuFDNOMYNfPEmfNTPO5dBIqf46ehLKOEuMf2QOTHX2x/CDdcELzMa/DJ/qq7VxJbmxE7vTcRkLCAzFII1G/bsqChgP3f1iDnODKX1lL9KLoy7dNjriv0tI4sQGWLVQJFQBtSqcB8cxec+NXxfOIhBlbEYoATEEYVuy3KAdyNv1f762e32YCetLDfNWKf7XH1NOsAH6eqsdB61joG0ZN3zdny6if5Xu3TPcs3N7jKFAPJY2O6UD2I8w5qhJQxlT0/WGZ6VHqVjLJVnAwKcvrDrayXBMA8AB7P8bxSCaJ0Cm6CQBCb7TxEZS2UHfgdNmWZIsKWVTpeE+1R65sK3BOuKwVMa9y/6yOoGiE/g4qxbYLxEd6Zg6RdhVyGH0HNiMfFFPxSQFzrjxNxCLhKhrSdO2myrsPRBMoatwQShw8gwX7RcsjhD/NAjkb5GBmors56fTjXMbOcjtnQXHVzPKknr/PjxbOtSoGBlqrM5V7pqx/r7ST9XjkFikuuYnjaX8Wy9n3RNPLJUKb8CzTGGaCCvoUg="  
  on:
    tags: true
