language: python
python:
- '2.7'
- '3.6'
install:
- pip install .
- pip install -r requirements_dev.txt
script:
- make test
cache:
  directories:
  - "./.hypothesis"
deploy:
  provider: pypi
  user:
    secure: 6y/5ZnnYsoLYn1QZ5ZoFrOBVphluunrEZUcNdNhFWj0TJwgX/s2W+l4lB2N7EtANKbiGjQfWFa1vBBZ//lWNnJtDnBstX9Lu/mHHXBe+2i6/eMm+C5tK3zifRKxawVHP3nUcC5mn/ITTCU3FNkT4RVPWZQbV8zoPMdsvk6dO/oOTZta+Ttt666iI52vGYZ3r2qfRSTi7GBCBBE2rwndRdRpzGtR3cGso02kpmEVM6FQxF8MOTTCPHKSAp6baKqHM0I7cJVz7X8kcZ5+0emJrCNCQAX1WJgoIU6gUIwMt2+3xW31C6r8a/rujvMVKstr+rwNJ3nD0MqFyN6Obha7YLFlsKqzuCNJKcx5v+2zpZMgZaovYgCQVLuwzRjPuQ7a2hnwYrF2HOIlrgtMlEJiFLUfDne6E5FykpOUkooVoyw+HrXLfivu+3vq0UbsAc5rL9a1iZCJFn2MxDV3G9MbPQIQkHzP5mayfVjf2kr07Be6ynjS0YffYcOFcJubB680MrnOMX4Qc9akCI1HTlN73K4G0alqI5PskfQ12s2Djbdl3v67v7XUQDzTC/TsFOGzfNoV4DC95snsVzmiEW1TTSLW7N7LBCNaoLdeEu5LyAPOchQhzOEQod+9FGGf39+lB2+ezEM01eF5liU+cGBWRXj8j5iRYprLkab461aGNjco=
  password:
    secure: SnbXU539rBCsgs9Q/yIR/ZNoPZ7T+qfTBogYhIHAgodntZw2VuffzK8Eb85bDlVCSXIrg7ezhzNJCDSVmYwyeOqdNqItfql/+Qo0RGvWKG5adfdxC7uA+OLM71YjzqSUfsPVMgKQwWQZdLvVhZKaGNLYDyuTqS6nban59C8W4w8cXUnaaNMFqNLzcjqU5UgjqXFHadFOq2GY965rTGqMgjM9+JxyQ6DU+G/c6u9ldxdNGojo+mFTrYhUYsnT1PfaCCoGKAhl7SAh6yHlIQ1Dmorx2tSm/jtlCboRKyXxJQoRiAvZLBRG/vDOivqrugwGc1oc6oM2LbQsHtVRbdnjpWBqEKWp3w0B9y7lnFzr5gdlQFbBwWy8/gMrkDRQqOsl8XAw0liJqR+1kBFL3OZfUeR+EMinuW1Ou8659qPewXE6yiRRmqtz1zbpQ3WR6xDiqMu44UNpp1B/SbxQEDV1RtQa4CSL2xteab+4UwP55QA+czbr7lPThI8w8BKbQQm8k+6uo8e+qhkjQea7VFzqkkhYD1xMdNxN/Q2IEzTRKLZEqn7k8B0AloiohbQHI722JhfZkX5Td7KTNj3O1K4QmRGIwHG1FVprlZbsadbSAbo2TngtX55/S1EWipGx9H7czRH/zonzsYTLM1Pa+5jlwQkcqxfBI0h2HOTW0Idw0iI=
  on:
    tags: true
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      - secure: e25t+8PyQL09v9korfscJaGl5p5gQDpjU+i+BYIjqX8jAl/SOcfYlZbOpfDeP+TjjIc37Dk7I6O7z4kBUpranyMdeIW9z3GvnQNOW00yBKYh/vmu3AGsGYWP7EmCDQFqIl2IBs8Du3QBJ1L0hrTTSXoH8RlIvYsK/G1olTVrX4emQnA08LVpqklIz5rc79Lp3VgEtpw6Syi2xkBoW+mEEiAOlxULRRp2m5sv5LuTru5FsfGTfSpk7Qes8/cutvFG8Ip541xSwgNKNXnC2QCREvtgUp7H+HclchRh6J2Cmh3TbC2s7o1pMDJMJRoGC+uL4aj8mSsiwHZV7+YbUD3fLH1dL/jR5UjkB727bKFcN6tNta938aIM5iYr5krX5SY/3+c2prg3Nf30JSCEp7ulRCe7lxbmIcWGF6SQD2ah+eLdqSFcVy/92z1EB9mlKL7rHyPcxcPMFXwXyaO/pB9u2ZO9DBDdtC9D5Of5vW08qzr/X9KTXwSxNCrQt4KOrrl4IpEQ5u4MtcXPXAw81ccUMNayFU3IXjB1c/eYjFvm70MzrMhgr+7szcwkarEwQXH/UPi/ionIXk6IlLp9lurFHZxXZ4tnos//4xILBPxG3xtAWOmkYeFnAcmzcOREa8tCh96NLGqhoL4SWvAGppmIv5CEuMlu4fdZp0cU2UZkXvw=
