language: python
python:
  - '2.7'
  - '3.6'
install:
  - pip install .
  - pip install -r requirements_dev.txt
script:
  - make test
cache:
  directories:
    - "$HOME/.hypothesis"
deploy:
  provider: pypi
  on:
    repo: Nike-Inc/signal_analog
    tags: true
  user:
    secure: aLkucDNerVMHl3S6lafXet1lThbkJMFcWPk5VZBvdIDNrIrsDouKuNVy9lCd8N4ia1KrJNB+M+p9fNuawQFEkcbfR4GtpLaahJY8SvJd6fQs1u/NKtOEluLVy2nHrmS5hue7/LT/U2UD8WvsbzryRifrXYCkSBE7FlCDm5q8InjQrxHV1u2BcGukDi/pgM3q6bAR8BQWvKp540PYv2nwh5SUGd3dlVAXzIh8B7T0QWDP+pSGZxJ6pJl72l/lYzcX1s08x70219TTMwNRxERKuNf4MX5Mw+ztC/4w7UV7jgCCZnh4ZsFuIyWVi13Vjpf4+CWrickGbFgt5/uWKLTip9BaGIm8WPXF2KfR+wPY+KXGycC31vKmzrUHsLMFTMzt7ZBkEoyw8rt+02jluoPrgj/mmJ8osmRWA/2KoUrNxdi4qm5qL8nSUftd0TE128KI3y8FCOwzL/oMZOeLXcDEbl1FJBnuEjLBF+/UfQaEx72BWN8gpkoqzIss3DoaGzFHiRFjhXR3r14u6jrzj9nyyZLPq1oHf5QkYuQ2IrdBa1cwJSB1yguOKN2ZMwViWKVzJ52B5jaSyQ3W48FNWeXP/smMKVnphIKTA1cctbYEUMMjCJoFl+dKBLWuJsPS8TypvRntiFcLgaCpuQAnIL7ityr7p97ws//KV9FqTNY4VUg=
  password:
    secure: QLtEswDyN0Lo4+B2OFo4WciOhb3ZMfQLaVMd1eT1g+a6qo7gb4S5xHUD2SxJf/EvYXOuHqp8HBkyEU/21esOp8FM008/y829u9jvTalDABlO29qIDLf1cMTZIlyqXr98wpODMn/yNvf1D7PmOzEdufyN0a6RQxCcJ4yutQG8YCeS9KjrqCid0+HufStlsKVF+HaWUQvDtMIvd28tYuFGZSx12gHffFyj6R3N3EaJKnbkNIy9vUZhRXvg+73bbViVVc4pKFuzgWvPjKnjLqNBVqSlj5Tcbn7kpGroaldQp7Bxqw3yTqvIZWRLaNEXmmyqlUdM6z/QakjHXHgayiMTtQfaOebB6bFXzgqAhsNtAM1Myysg7zbjOjg1kZ0bFizRqpvWhWlUHUDLtJGvChEcaLf6W7or5PozT1bl4N/i5MGcCdN6R98pfIHBFYlBlHVj5TpwSWroAa5JH1cKDxbWMxDUQr+JnS6hC85EYzL4SLndjgTuUjiQhudi7QJlOoM7zuIEQTK3pWQ059LtAJBnFNSQezDLp6N/3riR1mk74fLQSNkRPGzthEk0/xuYV6KSaCzvDur/x1+mbnqKOheLwcSzes55SPLuejEjPZ+qgZdzZ+CTLOyg6rL/iWfVyb/eJbiUmMcHZG5jYRRPCa3fv1ys5oeSxv/ziIXXKoobzeg=
