language: python
python:
  - '2.7'
  - '3.6'
install:
  - pip install .
  - pip install -r requirements_dev.txt
script:
  - make test
cache:
  directories:
    - "./.hypothesis"
deploy:
  provider: pypi
  user:
    secure: "OuYgIvyDkI5qiaDyvdDc831Kq1tcuSVyqX9j5HBXpy+IM4znFbuc4BTGyFtpXHug1/k1idmYewCUY6P3vgy3BLNpCxgHp/LtgiUg/JcULqUreSa4bIGS3i3B4fpvpGYrI2fNfYXdD01iqVW4ESbKymCwxPG8by3zZrGz+Srsa2PfbEGZKkLI1JXnep+omaEYrz0RDRwwGId3UZq/8KPWnZW1LkdZS31JonflhTgOcuwBHRFJexPO7so0QFSPvTn353QTsj7T7HtQEia1skuy2c1ApLLAVPP1P8sKijInwuzmAxtuXuhS11iNxClxKaIui9aGE7/QXkzumwPGsSBKfKwIQRmXbA/UZBAid1YDirVlSfulGaoQOBLHl5KljT5tWbeZUmm3j/etRG4bebDObk+c72bZpJ2aa+aypOTUc+yymmWDbunGczcbtrAh5rABrXu87tsmiKgiQh0bOAT3OxtLRgGctHAsPpgApnbEvEMMmitv87v1EeBwrXpiIhKL50a+PTROIETYjU+K90ix9Jol0+W3qbOVP8rv7mRyeq5njpWQwYiDcHugbGrazp/NwGyK9SLu+wwdhKf6P0RQaonFNVrCXfQBRs5QlrxeI3xKgPs9MGiEZiPCm0P6g7Lq7dOzVqKU8YfO4pMUjE2laLa6vEk0AKxTJ7tEbFga+AQ="
  password:
    secure: "VpWt2LFnPlVDlAjr2XAexnfPvx9Xj2RiCqXjBEzTEqJUb3SE8hsc7iBWdH6o2xiACDFNeq4OnTfsfJtRvjRbm3/xgvwLMDnAinFMVsrvktAtJW+FFSSJVsIJZ3D+drtfzuPJUwZCis0s5V0EuX6eWyBlgAfxLNwylhN8Nkna/Yr9JXueftnKxNj3sSsaRvDtDTNAQzOiGpKZPcm7oVs+H7lomL3rR7CcfvsfFlDs+ZSKe1XOCC50/gbL2XYEvTNyaA8/rJL2fYE1b5vYPiBZRXxpWrR6S/hcrDYb3Sq86mjXOzysDOh7toFUgTKD83CyGXOcabFwtrUbi6MBzwnsfnfLVDlB826TFz3Qg/2zaaLo65YeaTq7+JLGIU9bsbUJ97SpbWCP9Txdh8TmZGHuiD9nvMJJbW5YP5ovFGOFzowEMclFWsN/6TRe4Z6dwvgegap0BDZoTYmO2CdyD4d+eOUPCcrbzs4CYjrTTI8K2dhq4T3pOae2vaU90xcWIfR9V8PvkgHOmXXIlIVGc9QKQHHKSq//HEbaahZ17DrJjRRqqHnDBJ3ret1AfRFvrkQOHY/Cmj4RclTKEkugFBxFoy+hJkNSOCa4H8DihJd06RVv5jRlPvLG6/09ZgeUmkAqscA4YxbOUbCaTI9xYprKxNGCgDBjJ7ZxSyLOQnTDM44="  
  on:
    repo: Nike-Inc/signal_analog
    tags: true
