language: python
python:
  - '2.7'
  - '3.6'
install:
  - pip install .
  - pip install -r requirements_dev.txt
script:
  - make test
cache:
  directories:
    - "./.hypothesis"
deploy:
  provider: pypi
  user: nikeoss
  password:
    secure: "SnbXU539rBCsgs9Q/yIR/ZNoPZ7T+qfTBogYhIHAgodntZw2VuffzK8Eb85bDlVCSXIrg7ezhzNJCDSVmYwyeOqdNqItfql/+Qo0RGvWKG5adfdxC7uA+OLM71YjzqSUfsPVMgKQwWQZdLvVhZKaGNLYDyuTqS6nban59C8W4w8cXUnaaNMFqNLzcjqU5UgjqXFHadFOq2GY965rTGqMgjM9+JxyQ6DU+G/c6u9ldxdNGojo+mFTrYhUYsnT1PfaCCoGKAhl7SAh6yHlIQ1Dmorx2tSm/jtlCboRKyXxJQoRiAvZLBRG/vDOivqrugwGc1oc6oM2LbQsHtVRbdnjpWBqEKWp3w0B9y7lnFzr5gdlQFbBwWy8/gMrkDRQqOsl8XAw0liJqR+1kBFL3OZfUeR+EMinuW1Ou8659qPewXE6yiRRmqtz1zbpQ3WR6xDiqMu44UNpp1B/SbxQEDV1RtQa4CSL2xteab+4UwP55QA+czbr7lPThI8w8BKbQQm8k+6uo8e+qhkjQea7VFzqkkhYD1xMdNxN/Q2IEzTRKLZEqn7k8B0AloiohbQHI722JhfZkX5Td7KTNj3O1K4QmRGIwHG1FVprlZbsadbSAbo2TngtX55/S1EWipGx9H7czRH/zonzsYTLM1Pa+5jlwQkcqxfBI0h2HOTW0Idw0iI="
  on:
    tags: true
