language: python
python:
  - '2.7'
  - '3.6'
install:
  - pip install .
  - pip install -r requirements_dev.txt
script:
  - make test
cache:
  directories:
    - "./.hypothesis"
deploy:
  provider: pypi
  on:
    repo: Nike-Inc/signal_analog
    tags: true
  user:
    secure: D3IAB707M/cMOWuUJ9aG18ImCOdYJ7jwgUD/gPE/WB6hO9WE/mC7USMaqavGX1mHmPdH9nwE0p4tBwaqbOTW8XVn8G/tF+X4nnMFoWxqaYJHKiiC0zLsUeAMKkxoH6kQCs27wkeBr/zTWY/bJl9iLIlzILOl63dlDaVJjrpaXkwmaSpXKVLgNmc8PGoCOz/J/bSBXLhZMh7YMZDSdolc25Mp4obFHTW8MSSlzK9PwWuMwQuNs7xEPodMyY6cOxlKO7B/46gACq0OpT4LTOjLYGfWQyBhNlXt+1iCbdyAUI5kJltrAfpaHQNZnTFyx9SKcGYVvfczbB+tQkC95IYcKjyndkfiboayjxNggHm1jH8zKVy5iGOmaLG3EtnKTLdf4W0Tkme/vukXKx8CIWPzvgX06BMNzu0qm5QKOs9Zilx3MZtkvYI/TY9KmjN7oIjLT5l/4ynjZ/jh06Aj/1tR+pzOXS73NkdS7E0fEfV6421bGKUiHW0Sxii/AevvTPDe9t3ALSkqAtb8IHiuuVHDWg6YWAwwc6xnCFlYE/OajyuvFkUZ5DlyvdiwEhJAKad3znX3v5ZXv7oqcLjSiplkjUf7ctba+Qnkv49P8OXOHgXKo2wjBsV4K/vlZYKaRmYYXZBXMNR+AWS02qhMdcNwJt0UnOkHJgkI2EteQ1smpAA=
  password:
    secure: Bb5LdcV1rTfggyGVFs6B7w+yDOmbNNgOXOWMb2HO7VRmUfAPA1PQvrvVHvrAciCgwOeK/RRuUm6U3HMZmuToFNnA9ttN9hkUH83tCqZ9SqqTl504gwociiv9B52D1scCYgYk7tdZSWqS+Zl6oXESebG4voxjDrYgi3LIp+z0cGmYRYu1sGlF5scH5xRYpN5a/CVdMqtAS5UEp1CXm5wSmk2I3wumqYbSGm2LOZYKdzbn7/wtXZxcbLPt8Kl2onYv/H5GsXjdsqYW7ol4v1fdGoJ2rkqWRNA7BI1+DKwps8IVB2Rq8EBHBe3DhF6lA/2bMRf1vYMYtIwvoL/IvU7XmJPIL/TqzjCZRIqnopF9fcARkpS0jTW1mAVf5fxB0B2Cf4n+LnuFEaZgp9BtLG94/oaNeVCa2WgJWFkwtSFYiokprr42y5/yZsXJOOQkMC2XARHOvzFD9imXDW4H9akOjWcy75EXSCKfquDeARcbPafY1lWcdraTI4zCI6hTcn6ByQerxa3PAEXHlyVZO3t7O39ix2/wwxadnT+Y/D5VIBRYLYm/Mm0Skjyo98miFaqWUvxiYx3z6jdJJ3dhkrVowJDzCtpJfcS2EULjHhXXev529EelgtjIAwqipw0q5jnpS2g9ULXI27zh7/Fitc5YPFi5+MM44x1MKRW6PRDxqTI=
