language: python
python:
  - '2.7'
  - '3.6'
install:
  - pip install .
  - pip install -r requirements_dev.txt
script:
  - make test
cache:
  directories:
    - "./.hypothesis"
deploy:
  provider: pypi
  on:
    repo: Nike-Inc/signal_analog
    tags: true
  user:
    secure: HPj+ZZJZFqU7ZtfZzzBGkG9fsXHpeRKNprtlod/BIl3bJlwCkl1fz/oiisYkjmzjdX6lSSPaUlsVuER+L3rrSSM5Yiw/biBVIHAWRKDXr2RpefMTxoLId22sdaUnxht5EJPN2iQOEmpNLrqNjXkCbnHn7ZblOBkxg7uXjjvzH0udLYjtTXpa/gTnbVwoKDgKkuqiVd6O6kn3HT95p7iosdBuj8eqvZqNG+d57/YgXMfR3w6lXNRcAVUIVS+MHkGAt4zg+K36GlqSeECN7LDUhM5ESqaX9JZwtjT2smSkFkow8LapkCm5Qfwf/IQn5s57B4YZJgaccq3x5aYSpQpj2fHkUMqAX0etcEGIUtwGICwGg026lavMh+lIgqP5jrS+IPia1XLFbA57qSDqIhxJLTVizu54oKPSO2ZaTQSYU+rrU/owVNBrjolA2y4s+6NcS9SYsKLXMcPTDRbRNpCeJBY883Y90VLVfchCuWU48TXIEsyDDOgDng53Ycy8Y1K4+S4zoJU90775JlxiuszXU7qp9PVFtVe1t4f+svIQ9WFqRPxVsIidjKlaiDNmcyCD/f1RKth+JCufPFlEv2kLo8vr08gEMCUYqKMGGTwpNK7EG8/mr3bjwLtJyrBY4Itn5zDiN2dwLz2dFs857z+7OfNQ9LQl6mtPpB0aeEz7jk4=
  password:
    secure: rTmNJkgiVq2dHIoK130KAG6aUf8uojnLo6i64mnu/lUyqAgSyFWE0wX0sPP96Rar+vP1AXJ0Gd1an6aml1GH2tRkpoW1sAqMiC2gArxAbDWDbm9mQVgDfGYvABGBJeHpvL8GfwBreLgN7adfVGYGINdG4JQ/4jRWDwV4y7yaJeDA4CDVLnFJ1sT5ZEv8v5FnAYZE/FM9E4IuNlsjj7Sfces2WaSJG0+yazf68ngomhiqeCXR9ejPjNVyCltEGdPPKTSWyQ2WcdmiaqIXu7sKvffymys0/u94kXolBT7v3eFrPR+AWwmL58OUXSXUYwC003wLZWmuGlc+YL2SooJo1gwzdIRPMZxD3YGTroH3lQUEuGaADGFBPdM6zf50SXjV+AvwtJATGHcKlUja2XFhtihzxn2TLFt6lBgrgNp0iTuA8uFKaef5LDA3yYwhxugofeh6XfOACDO/J2OwPrZZVNvDnxqPndlxu0NVKLKcGzJg5lDQTnK64NJVepMzFPgjcmC8wuGgwxy97jE73VSSjeSkMXIriPErw2N8tpl4l60HbRsasgC2Z7lV7l7qgGeigovGSoGaFbtrDXXLEDVwDMfrfImG1CIbLHulU8VtX6ma8n3O7/LHsN5VbW89hClq6yoI04IKTWx1dxOekAJmplKZM/RHNQtIyQv3qju4Cmo=
