language: python
python:
  - '2.7'
  - '3.6'
install:
  - pip install .
  - pip install -r requirements_dev.txt
script:
  - make test
cache:
  directories:
    - "./.hypothesis"
deploy:
  provider: pypi
  on:
    repo: Nike-Inc/signal_analog
    tags: true
  user:
    secure: "HPj+ZZJZFqU7ZtfZzzBGkG9fsXHpeRKNprtlod/BIl3bJlwCkl1fz/oiisYkjmzjdX6lSSPaUlsVuER+L3rrSSM5Yiw/biBVIHAWRKDXr2RpefMTxoLId22sdaUnxht5EJPN2iQOEmpNLrqNjXkCbnHn7ZblOBkxg7uXjjvzH0udLYjtTXpa/gTnbVwoKDgKkuqiVd6O6kn3HT95p7iosdBuj8eqvZqNG+d57/YgXMfR3w6lXNRcAVUIVS+MHkGAt4zg+K36GlqSeECN7LDUhM5ESqaX9JZwtjT2smSkFkow8LapkCm5Qfwf/IQn5s57B4YZJgaccq3x5aYSpQpj2fHkUMqAX0etcEGIUtwGICwGg026lavMh+lIgqP5jrS+IPia1XLFbA57qSDqIhxJLTVizu54oKPSO2ZaTQSYU+rrU/owVNBrjolA2y4s+6NcS9SYsKLXMcPTDRbRNpCeJBY883Y90VLVfchCuWU48TXIEsyDDOgDng53Ycy8Y1K4+S4zoJU90775JlxiuszXU7qp9PVFtVe1t4f+svIQ9WFqRPxVsIidjKlaiDNmcyCD/f1RKth+JCufPFlEv2kLo8vr08gEMCUYqKMGGTwpNK7EG8/mr3bjwLtJyrBY4Itn5zDiN2dwLz2dFs857z+7OfNQ9LQl6mtPpB0aeEz7jk4="
  password:
    secure: "gHI0v6UQIYYe5o56klB6gvt17AKLVoS4eMsC1EUu8SCbk1hCPwnK4/g4Af64N9smp0DvS1Ifd2wfLcb/Emf8spOXOQM7/mebtZf+muzOZIeCzTxtm1gO85+CzZmPFv8QRpG6wawSLR1I5s0ubh9xJeBw9FU3BPtjjXWjQbgylnoH+VbbHxdR1F8ZlvheVILHxT5qfPv4JJvcHJNd5I2dDk/vLLYqk1nvhYCp7kVpFl4An8G6+op/zF6slUWBqwf/Sz6KWCaEDN+KnckZk1zdlvXfW85gkq758PgP94xSbT6SLMk/b/IYcHPpUJm2afN/1cxSXVPcisQaNeTESWFg9OLxAxzENF0AI4GcIdcTuVK9iZBoKwQzhL/kSwKp1LhFZm555/0UXoOjF7ZI3EtGGkENb0wJ+378LSLRXn5NextbsH7LBetQ2m02RWw40/7NJVQ+4xv9lrE3/XcRzJoGI8RgnseQL0vePLwwpvKXxbyDdOIuOl3zu3Ek5JpbGU+OgEY9y7RjEFqlYk/10w+aX9YxvCtG6s5eLvp5XirhnlHFr8i1jAmkpxgajn4gsmmrJeVUrGv/65v4fsbrh7h9anVEprbtRbWcXKj9mJEjLwvEQjtudRcyFvv6x0VFO3haZ19eFlMDWlN9PjdxKHOgrTtwPA/OpfGbf0CuCNrCF9k="
