language: python
python:
  - '2.7'
  - '3.6'
install:
  - pip install .
  - pip install -r requirements_dev.txt
script:
  - make test
cache:
  directories:
    - "./.hypothesis"
deploy:
  provider: pypi
  on:
    repo: Nike-Inc/signal_analog
    tags: true
  user:
    secure: HPj+ZZJZFqU7ZtfZzzBGkG9fsXHpeRKNprtlod/BIl3bJlwCkl1fz/oiisYkjmzjdX6lSSPaUlsVuER+L3rrSSM5Yiw/biBVIHAWRKDXr2RpefMTxoLId22sdaUnxht5EJPN2iQOEmpNLrqNjXkCbnHn7ZblOBkxg7uXjjvzH0udLYjtTXpa/gTnbVwoKDgKkuqiVd6O6kn3HT95p7iosdBuj8eqvZqNG+d57/YgXMfR3w6lXNRcAVUIVS+MHkGAt4zg+K36GlqSeECN7LDUhM5ESqaX9JZwtjT2smSkFkow8LapkCm5Qfwf/IQn5s57B4YZJgaccq3x5aYSpQpj2fHkUMqAX0etcEGIUtwGICwGg026lavMh+lIgqP5jrS+IPia1XLFbA57qSDqIhxJLTVizu54oKPSO2ZaTQSYU+rrU/owVNBrjolA2y4s+6NcS9SYsKLXMcPTDRbRNpCeJBY883Y90VLVfchCuWU48TXIEsyDDOgDng53Ycy8Y1K4+S4zoJU90775JlxiuszXU7qp9PVFtVe1t4f+svIQ9WFqRPxVsIidjKlaiDNmcyCD/f1RKth+JCufPFlEv2kLo8vr08gEMCUYqKMGGTwpNK7EG8/mr3bjwLtJyrBY4Itn5zDiN2dwLz2dFs857z+7OfNQ9LQl6mtPpB0aeEz7jk4=
  password:
    secure: D6dNllw2ZRBlD4HIN4xzkHM9te1g4djdDzJTt9ZAE6j5xP3XdHbmkEuQRbj92V6bYAop6mcLOEWmRBPtMmJOxOAz0KGBLVE+XM1kEES9JFd+pUnfxG+Pg89B7PD1pix5pW3TYPKrQ8RaZgC9orJl41e8IGtNg3tiEBjFKGMLEJmwv7bVYvk9UuBKS2NaBErEruVALqdzPyo05cyt3Bwf25sjGeorgvpedYfu7Y3gIkMPKc+QU7Hl/C51bnSaWqmFrhYv5P+WYh9Cs2qCkMjOJy9J8+i/QzOMemuTPfoh5q13maigEWeO9lPBbuDe/rDvtYfuhPbebYJyzjO6s520f7d+bwhUI2BdfIeH9zokN2mw/+shKDko/FuWPRWLD/OviP5DeojN5HVuWjeU0hoXDLN5tItS44nZsjmYBYbvBuTffefIhKKcSD2mKQRv4h3jHj3eHgtmw3R2NRnn8zK9rnYMtGDkFNIX+4/tMCNH+iNrb0iryvTimP1yy6cJNjUFibeBkHqmKmrfCLq9FPN1Ry2W10p7oo87myJrCMen3XPjA0ycNA++lilDqi0EXJKQurz8oUKuoqw13dYTSXjNnoB50IH2uEqTltbkF8/BEDtiafTOKgkrHvkmLCeg/o7TqMprH7lk/jhdbM5CN1jnLa6gGs+5NC6rwcDsYcpUPhc=
