language: python
python:
  - '2.7'
  - '3.6'
install:
  - pip install .
  - pip install -r requirements_dev.txt
script:
  - make test
cache:
  directories:
    - "./.hypothesis"
deploy:
  provider: pypi
  on:
    repo: Nike-Inc/signal_analog
    tags: true
  user:
    secure: "HPj+ZZJZFqU7ZtfZzzBGkG9fsXHpeRKNprtlod/BIl3bJlwCkl1fz/oiisYkjmzjdX6lSSPaUlsVuER+L3rrSSM5Yiw/biBVIHAWRKDXr2RpefMTxoLId22sdaUnxht5EJPN2iQOEmpNLrqNjXkCbnHn7ZblOBkxg7uXjjvzH0udLYjtTXpa/gTnbVwoKDgKkuqiVd6O6kn3HT95p7iosdBuj8eqvZqNG+d57/YgXMfR3w6lXNRcAVUIVS+MHkGAt4zg+K36GlqSeECN7LDUhM5ESqaX9JZwtjT2smSkFkow8LapkCm5Qfwf/IQn5s57B4YZJgaccq3x5aYSpQpj2fHkUMqAX0etcEGIUtwGICwGg026lavMh+lIgqP5jrS+IPia1XLFbA57qSDqIhxJLTVizu54oKPSO2ZaTQSYU+rrU/owVNBrjolA2y4s+6NcS9SYsKLXMcPTDRbRNpCeJBY883Y90VLVfchCuWU48TXIEsyDDOgDng53Ycy8Y1K4+S4zoJU90775JlxiuszXU7qp9PVFtVe1t4f+svIQ9WFqRPxVsIidjKlaiDNmcyCD/f1RKth+JCufPFlEv2kLo8vr08gEMCUYqKMGGTwpNK7EG8/mr3bjwLtJyrBY4Itn5zDiN2dwLz2dFs857z+7OfNQ9LQl6mtPpB0aeEz7jk4="
  password:
    secure: "UtCiP1PzxOrg0uAHewCuvgPosdsTelMY+zPKXV8JTWfqFdVkv9wuWK2y081Dkiqp2ypwXH6XMj3nWRz9K17uxRq65v6tQQEoH04AOWKOMetmp41CUc1GAgrnfpSHYN9h2tIHE4NR2A8IE4M5Ow/UcTzTb+rSake7d10yrSITY36m5uEpYBt81tOWPMyDpcVrFeZsowTm17QBEcp4hhp4leE0Qhra2MT+jJ/0qiqvN2FDec39Iab8Dz5PHVxGgcpFW6wgw5uaqKz4Fsnd5aZVKuBoRbZXhvvOzGS1d4GVGtH6F7haCFQgZ6apSa7csNnAh2d8rEKCMh0JhrfLKk1vZAllWdL4qFA+zdNuLdaxGgYPvzLhAOHVMUOvm7paDtG1tkvlBSZBbSN+F/CJ/vu+PTe00WHHTPoQRsIzAQoq5+0W/pVTeavDZngPP9ChB5vvqQkpxTdcHpcwK32qp4VvnMz+lywEFpQmzBVlyB7SfbQo+ACscmmFa07Xqel/a1u2JZVpSZRpSqfXLjPa3x3fk/143kLZqmtq1Dv8GNVJUc09jegz91atRkr2j8SoAmWOqFIvBD/HHUWzY6YFR2WdpljCAC5cgCe6+vs8/o3JWMFeMl0Ldc2MTps8+S3ZE2xhG9tUuQWd3ESkyLyvPikESXUn1nW5JO2QACvjdwTxyLE="
